apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: myapp

spec:
  minReplicas: 2
  maxReplicas: 8
  targetCPUUtilizationPercentage: 30
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: myapp